name: "Setup python dependencies"
description: "Install poetry and python dependencies"
runs:
  using: "composite"
  steps:
    - name: Install poetry
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      shell: bash
      run: |
        poetry config virtualenvs.create false
        poetry install
