name: "Test"
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  format:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_python
      - name: Test code formatting
        run: make test-format
  import:
    name: Check import formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_python
      - name: Check import formatting
        run: make test-import
  lint:
    name: Check code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_python
      - name: Check code linting
        run: make test-lint
  types:
    name: Check type annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_python
      - name: Check type annotations
        run: make test-types
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup_python
      - name: Run unit tests
        run: make test-unit
